#!/usr/bin/python
import os
import shutil

import sys
import fileinput
file_name1 = raw_input("Enter the file name ")
print file_name1
file_name = file_name1.lower()
print file_name
name_upper = file_name.upper()
print name_upper
full_name = file_name + '.cfg'
print full_name
port = '20' + file_name[-2:]
print port
cells_xml_value = file_name[-2:] + '5'
print cells_xml_value
xml_name = file_name + '.xml'
print xml_name

cells_xml_name = file_name + '_cells.xml'
print cells_xml_name
lmt = raw_input("The LMT IP address: ")
oam = raw_input("The OAM IP addresss: ")
tna = raw_input("The Traffic(tna) IP address: ")

enbid = '3000' + str(int(file_name[-1:]) + 60)
print enbid



		for i, line in enumerate(fileinput.input('/home/eravarm/Desktop/auto/'+'RBSNC_2_basic_fru_netconf_create_common.xml', inplace=1)):
			
    			sys.stdout.write(line.replace('10.94.71.150/24', tna))
		for i, line in enumerate(fileinput.input('/home/eravarm/Desktop/auto/'+'RBSNC_2_basic_fru_netconf_create_common.xml', inplace=1)):
			
    			sys.stdout.write(line.replace('132.196.236.152/24', oam))
		for i, line in enumerate(fileinput.input('/home/eravarm/Desktop/auto/'+'RBSNC_2_basic_fru_netconf_create_common.xml', inplace=1)):
    			sys.stdout.write(line.replace('300061', '300067'))
